version: '3.3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - data:/data
      - ./config/redis.conf:/usr/local/redis/redis.conf

  backend:
    image: api-server
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - '8081:8081'
    env_file:
      - .env

volumes:
  data:
    driver: local