@url = http://127.0.0.1:8081/api
@adminCreds = <secret>

###
### Get all blogs
###
GET {{url}}/blogs
# http://localhost:8081/api/blogs

###
### Search by blog title
GET {{url}}/blogs?q=Hallo
# http://localhost:8081/api/blogs?q=

###
### Get blog by id
###
@uuid = 71026c3f-82b4-4f77-81c4-417f29455d88

GET {{url}}/blogs/{{uuid}}
# http://localhost:8081/api/blogs$(blog.uuid)

###
### Write a blog entry
###
POST {{url}}/blogs
Content-Type: application/json
# http://localhost:8081/api/blogs

{
  "author": "Anonym",
  "title": "Hallo",
  "content": "Das ist ein Hallo"
}

###
### Delete a blog by id
###
DELETE {{url}}/blogs/{{uuid}}
Authorization: ApiKey {{adminCreds}}
# http://localhost:8081/api/blogs/$(blog.uuid)